# Generated by Django 2.2 on 2019-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=150)),
                ('tutorial_content', models.TextField(blank=True)),
                ('tutorial_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
